dependencies:
  - name: postgresql
    version: 0.15.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: nginx-ingress
    version: 0.15.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: cert-manager
    version: v0.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
