enabled: true
initializeDb: false
loomio:
  RAILS_ENV: production
  image:
    repository: loomio/loomio
    tag: stable

mailin:
  image:
    repository: loomio/mailin-docker
    tag: latest

postgres:
nginx-ingress:
  rbac:
    serviceAccountName: "ingress"
  controller:
    hostNetwork: true
    service:
      type: NodePort
      annotations:
        kubernetes.io/ingress.class: nginx
      nodePorts:
        http: "30284"
      targetPorts:
        http: http
        https: http
cert-manager:
  replicaCount: 1
