enabled: true
initializeDb: false
loomio:
  RAILS_ENV: production
  image:
    repository: loomio/loomio
    tag: stable

mailin:
  image:
    repository: loomio/mailin-docker
    tag: latest

postgres:
nginx-ingress:
  rbac:
    serviceAccountName: "ingress"
  controller:
    hostNetwork: true
    service:
      type: NodePort
      annotations:
        kubernetes.io/ingress.class: nginx
      nodePorts:
        http: "30284"
        https: "31968"
      targetPorts:
        http: http
        https: https
cert-manager:
  replicaCount: 1
nfs-client-provisioner:
  nfs:
    server: eks.mayara.io
    path: /
  storageClass:
    name: loomio-nfs-client
