kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loomio-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loomio-db-4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
